### ISSUE TITLE
It's a fantastic project.But is this code repository no longer maintained?

### ISSUE THREAD

**Issue by git-cncoder** [AImarkdown/main#2]
It's a fantastic project.But is this code repository no longer maintained?
I've noticed that the project hasn't made any progress in the past 4 months.

**Comment by simplertasks** [comment]
> It's a fantastic project.But is this code repository no longer maintained?
> 
> I've noticed that the project hasn't made any progress in the past 4 months.

I intend to get back to this project very soon and actively maintain it as I think it may have a great future, I'm looking for some assistance from the community as well   

Thank you for your comments

**Comment by AImarkdown** [comment]
I’m continuing development and you can have a look here to see what’s new

AIDataDoc 

https://hackernoon.com/aidatadoc-chatgpt-web-technologies-one-file-to-rule-them-all-open-source-simple-portable
